# A nixpkgs-style derivation, in the shape `pkgs/by-name` wants so it can be
# submitted upstream with only the path changed.
#
# Build it from a checkout with:
#
#   nix-build packaging/nix -A marquee-markdown
#
# `cargoHash` pins the vendored dependency tree and changes whenever
# `Cargo.lock` does. Nix prints the correct value when it disagrees; paste
# that in rather than guessing.

{
  lib,
  rustPlatform,
  fetchFromGitHub,
  installShellFiles,
  versionCheckHook,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "marquee-markdown";
  version = "0.9.0";

  src = fetchFromGitHub {
    owner = "SophanaSok";
    repo = "marquee-markdown";
    tag = "v${finalAttrs.version}";
    hash = "sha256-au4JAmk1OiBWWQwEjiL0pCBrH00dj4n2LASmFt/Ib8I=";
  };

  cargoHash = "sha256-1iEpLTcqCm0pRou90d3aYkY3mvmg4aTu9ZiNOp/SvGE=";

  nativeBuildInputs = [ installShellFiles ];

  # Syntax highlighting uses a pure-Rust regex backend on purpose, so there is
  # no C toolchain and no system library to find. Nothing belongs here.
  buildInputs = [ ];

  # The live-forge checks are `#[ignore]`d, so the suite needs no network.
  # `--all-targets` skips doctests, and the render module's public example is
  # one, so both are run.
  checkFlags = [ ];

  postInstall = ''
    # Generated by the binaries themselves, so they cannot drift from the
    # flags actually accepted. Both names, because a completion registered for
    # a name the reader does not type never fires.
    for name in marquee-markdown mmd; do
      # `--name` because the page arrives on a process substitution, which is
      # a named pipe: there is no `marquee-markdown.1` for the hook to read a
      # name and a section out of, and it refuses to guess.
      installManPage --name "$name.1" <("$out/bin/$name" man)
      installShellCompletion --cmd "$name" \
        --bash <("$out/bin/$name" completion bash) \
        --zsh <("$out/bin/$name" completion zsh) \
        --fish <("$out/bin/$name" completion fish)
    done
  '';

  nativeInstallCheckInputs = [ versionCheckHook ];
  versionCheckProgramArg = "--version";
  doInstallCheck = true;

  meta = {
    description = "TUI markdown reader that renders documents like Claude artifacts, with a table-of-contents panel";
    longDescription = ''
      A terminal markdown reader with the functionality of glow, rendering
      documents the way Claude artifacts do — a centered reading column on a
      painted page, typographic headings, sealed code cards — with a
      scroll-tracking table-of-contents panel and in-document search.

      Installs two commands, marquee-markdown and mmd, which are the same
      program under a shorter name.
    '';
    homepage = "https://github.com/SophanaSok/marquee-markdown";
    changelog = "https://github.com/SophanaSok/marquee-markdown/blob/v${finalAttrs.version}/CHANGELOG.md";
    license = lib.licenses.mit;
    # Required for a new package, and deliberately unresolvable until the
    # submission lands: `lib.maintainers.sophanasok` does not exist in nixpkgs
    # yet, so forcing this attribute — `nix-instantiate --eval --strict ...
    # .meta.maintainers` — fails with an undefined variable. `nix-build` is
    # unaffected, because `meta` is lazy and never forced by a build, which is
    # why the flow in README.md still works.
    #
    # The entry it refers to goes in `maintainers/maintainer-list.nix` in the
    # same pull request, which is what makes it resolve:
    #   sophanasok = {
    #     name = "Sophana Sok";
    #     github = "SophanaSok";
    #     githubId = 5224183;
    #   };
    maintainers = with lib.maintainers; [ sophanasok ];
    mainProgram = "mmd";
    platforms = lib.platforms.unix ++ lib.platforms.windows;
  };
})
