# Homebrew formula.
#
# The `url` and `sha256` are the source tarball for a tag, not the release
# archives: this formula builds with cargo, so the `checksums.txt` on the
# release describes files it never fetches. Bump it *after* pushing the tag —
# the hash cannot be computed before the tarball exists — with
# `brew bump-formula-pr --version=X.Y.Z`, which rewrites both lines and
# computes the hash itself.
#
# `tests/docs.rs` allows this to be one release behind the newest dated release
# in the changelog — the gap between the tag and the tap pull request — and
# fails at two. A formula nothing checks is how this one came to sit with no
# `url` at all through four releases.
class MarqueeMarkdown < Formula
  desc "TUI markdown reader that renders documents like Claude artifacts"
  homepage "https://github.com/SophanaSok/marquee-markdown"
  url "https://github.com/SophanaSok/marquee-markdown/archive/refs/tags/v0.6.0.tar.gz"
  sha256 "727292d74dba24c5697a16ee6b2f8bc8107300b81294fcc78c26a0c09b8b3a27"
  license "MIT"
  head "https://github.com/SophanaSok/marquee-markdown.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
    # Generated by the binaries themselves, so they cannot drift from the flags
    # actually accepted. Both names, because completions registered for a name
    # the reader does not type never fire.
    ["marquee-markdown", "mmd"].each do |name|
      generate_completions_from_executable(bin/name, "completion")
      (man1/"#{name}.1").write Utils.safe_popen_read(bin/name, "man")
    end
  end

  test do
    (testpath/"doc.md").write "# Title\n\nBody.\n"
    assert_match "Title", shell_output("#{bin}/marquee-markdown -w 40 doc.md")
    assert_match version.to_s, shell_output("#{bin}/marquee-markdown --version")
    assert_match "Title", shell_output("#{bin}/mmd -w 40 doc.md")
  end
end
