# Homebrew formula.
#
# The url and sha256 are filled in per release; `brew bump-formula-pr` does it
# from the checksums.txt attached to the GitHub release.
class MarqueeMarkdown < Formula
  desc "TUI markdown reader that renders documents like Claude artifacts"
  homepage "https://github.com/SophanaSok/marquee-markdown"
  license "MIT"
  head "https://github.com/SophanaSok/marquee-markdown.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
    # Generated by the binary itself, so they cannot drift from the flags it
    # actually accepts.
    generate_completions_from_executable(bin/"marquee-markdown", "completion")
    (man1/"marquee-markdown.1").write Utils.safe_popen_read(bin/"marquee-markdown", "man")
  end

  test do
    (testpath/"doc.md").write "# Title\n\nBody.\n"
    assert_match "Title", shell_output("#{bin}/marquee-markdown -w 40 doc.md")
    assert_match version.to_s, shell_output("#{bin}/marquee-markdown --version")
  end
end
